### ISSUE TITLE
Trying to install...

### ISSUE THREAD

**Issue by erkapekka** [ricrpi/mupen64plus#16]
Hello!

I am kind of a noob at this, and also at Linux, but when I'm trying to install mupen64plus with this package, it doesn't work, or maybe it's me that doesn't work ( :S ).
Anyway, I completed the build.sh script, and proceed to execute the install.sh script, It looks like this: http://i.imgur.com/SunKahV.png
Important to note, in that case, I tried with the "Install" but it neither works with that or "Install.sh".
Help is greatly appreciated!

**Comment by ricrpi** [comment]
Could you try running using 

$> ./install.sh 

as it uses /bin/sh instead of bash

**Comment by erkapekka** [comment]
Yeah I think I mentioned it, but I get the same response when I use ./
instead of bash, but I'll look into it!

måndag 16 februari 2015 skrev Richard Hender <notifications@github.com>:

**Comment by erkapekka** [comment]
Doesnt work ricrpi, unfortunately. Same error message.

**Comment by ricrpi** [comment]
There is an error 'Cannot find file: -e' which I think was thrown at the start of the script. Therefore it looks like the build script failed to download the various repositories you need resulting in the failure when you tried ./install.sh. 

Could you try running:
$> ./build.sh

**Comment by erkapekka** [comment]
Okay, so I updated the whole raspberry now, with: Sudo apt-get update, and Sudo apt-get upgrade, then I ran ./build.sh and ./install.sh, with sudo ofcourse, here's what happened.
http://i.imgur.com/tMRhUGl.png

**Comment by ricrpi** [comment]
Think its fixed now but can't test the script.

**Comment by erkapekka** [comment]
Should I re-download the folders and so? With apt-get?

**Comment by erkapekka** [comment]
Okay, so I did the git pull origin command, and it downloaded a couple of things. Then when I went to do the sudo ./build.sh script: this showed up: http://i.imgur.com/nVO7iB6.png
And so I did update the swapsize, and it sure updated: http://i.imgur.com/C0DH1nJ.png
Then when I went on to reboot, according to the swapsize file, it said in the reboot that it wasn't found. (?) It was there all along before even, but then it just said: CONF_SWAPSIZE=100
Anyway, I tried running the ./install.sh script again, and this was the message this time: http://i.imgur.com/gffDDjK.png

I'm very sorry if I'm disturbing in any way, but this is important for me, and all help is greatly appreciated, as I said. I'm doing this as sort of a end-term project, and it would be great if I got it working!

**Comment by ricrpi** [comment]
For reference, the install script is not intended to be used to build the code. You will know if it works because it takes an hour to compile SDL2 and another hour to compile mupen64plus and its plugins. 

I'm not sure why changing the swapfile size didn't work for you . Could you try setting it again using the following:

sudo nano /etc/dphys-swapfile
sudo dphys-swapfile setup
sudo dphys-swapfile swapon

once thats done if you do 'free -h -t' you should see ~750MB memory available on you Pi.

**Comment by erkapekka** [comment]
Keeps giving me the same error message that I didn't mention before, It says that it cant find CONF_SWAPSIZE. Might it be because of that I tried to edit it using Vim? I edited it that way and just changed 100 to >= 350.
Here's a pic: http://i.imgur.com/Wqej15e.png
And yes, on that last one when it says permission denied, if I run that with sudo, it still shows that it wasn't found..

**Comment by ricrpi** [comment]
sorry you need to set it like this:

CONF_SWAPSIZE=350 

(or greater)

**Comment by erkapekka** [comment]
Okay, so now the build.sh script didn't complain about little dphys-swapfile memory, though it now complained about this: http://i.imgur.com/Mv4pfl8.jpg
Seems like a weird error, because all raspberrys except Pi2 runs on the same CPU, right?

**Comment by gizmo98** [comment]
Try to install libpng12-dev with apt-get.

**Comment by erkapekka** [comment]
What's the command for that?

**Comment by gizmo98** [comment]
sudo apt-get update
sudo apt-get install libpng12-dev

**Comment by erkapekka** [comment]
Okay, seemed to have worked, now this showed up: http://i.imgur.com/w6JdZys.png

**Comment by erkapekka** [comment]
I've been investigating this, but I couldn't find anything that I believed could help, do you guys have any idea?

**Comment by ricrpi** [comment]
Its an issue with the Input Field Separater (IFS) within the build script. I've got a fix but want to tidy up a few other bits and test before script before releasing (probably tomorrow evening)

**Comment by ricrpi** [comment]
All done and tested

**Comment by erkapekka** [comment]
I noticed this right away, and I started the raspberry instantly, and ran the build.sh, still the same error: No OpenGL development libraries found.

**Comment by ricrpi** [comment]
Could you try using V=1 ./build.sh and provide all the output, please

**Comment by erkapekka** [comment]
(V=1) = version 1?

**Comment by ricrpi** [comment]
V for Verbose, setting the environment Variable V to 1 will output a little more debug info

**Comment by erkapekka** [comment]
Well this is basically it: http://i.imgur.com/jVJTiMq.jpg
http://i.imgur.com/p8M8Ew5.png

**Comment by ricrpi** [comment]
your script is out of date (by 6 updates), it was possible for an error to stop auto-updating, could you try running the following in your root mupen64plus folder:

git pull origin
git log -n 1

the log output should give you a commit hash ending with 030e3ee2

**Comment by erkapekka** [comment]
Okay, did this now: http://i.imgur.com/H1Pr6Hd.png
Obviously it didn't give the commit hash that you said, and so I figured I should just do this the right way; I reformat the SD-card, re-install Raspbian, update raspbian, then download these files, and try to install it again, if that don't work, well what can I do?
Am I like the only one having problems with this?

**Comment by ricrpi** [comment]
Don't worry about the hash, you have the most up-to-date build script now and rebuilding your system is a bit drastic. 

The problem is the Makefile doesn't appear to be picking up the flag USE_GLES=1. This flag comes from the RasbianList used by the build script. As a consequence the makefile sets OSD to 1 and then requires OpenGL libraries.

If you run using 'V=1 ./build.sh' the script will echo the command it is trying to use with the makefile. (Note that Input Field Separator variable can break command arguement parsing so the echo is no guarentee that the command printed is what was run). 

given the script uses /bin/bash could you try running 'bash --version'?
Also one final thing to try would be to add 'set -x' to the script around line 557. It may provide a clue on the make command.

**Comment by erkapekka** [comment]
Just so that we make things clear here; 
1. These files (the directory I downloaded from this site) are the only ones that I need to make mupen64plus Nintendo 64 Emulator to work on my Raspberry?

2. I previously downloaded some other directories from other sites and users that also would allow me to install mupen64plus, but are these somehow interfering with the files that you use?

3. If number two is true, that they are interfering, is the easiest solution to rebuild my system?


Now updating from your most recent post. I have now checked my bash version, and it is: http://i.imgur.com/7IfLl7w.png
I also ran the V=1 ./build.sh and it didn't display any other information other than what I've gotten before: http://i.imgur.com/DPbedBQ.png
And the 'set -x' I added to exactly line 557, on which it was no other code: http://i.imgur.com/NgGUwtG.png
You can see it on the bottom left corner, that is exactly line no 557

**Comment by gizmo98** [comment]
1. You only need these files.
2. If you use other packages different sdl2 installations "could" interfere. But this should not interfere with the build process.
3. You can do this. A clean system is always the best base.

If you want to use mupen64plus on a pi now use http://blog.petrockblock.com/retropie/retropie-downloads/download-info/retropie-sd-card-image-for-rpi-version-2/ or https://github.com/petrockblog/RetroPie-Setup. But it would be nice if you could help fix mupen64plus build script.

**Comment by ricrpi** [comment]
@erkapekka 
 
In answer to question 2, Retropie has its own equivalent of build.sh but it does not interfere as it generally builds in a different folder. I don't know about other build scripts.

I agree with @gizmo98 that it would be good to fix whatever issue is causingy you problems but also appreciate you probably want to get straight on with playing. If you want to carry on debugging then could you provide the output from running the build script with 'set -x' insterted? 

I am a little surprised that V=1 ./build.sh didn't work for you. I am wondering now if your ~/.bashrc file may have something in it thats causing problems... You could try renaming it to move it out the way, start a new shell and run the build script.

**Comment by erkapekka** [comment]
I will try my best to help you fixing this, but you've got to remember two things, I am not all too well familiar with Linux, and things that seem clear to you might not be as clear to me, and so I might not understand how to do everything. For example what you said ricrpi, the bashrc file, I guess lies in my root folder somewhere, but I dont understand the next part, how do I start a new shell?

Second thing to remember, I am doing this as a project in school, and although it would be fun to be able to play, getting it to work is my main priority, and since it has to be completed before week 13, I dont have lots of time to fiddle with this. I will have to try to get RetroPie to work.
I will be happy to help you guys with this build.sh script though, but as I said, you will have to provide clear instructions on how to do things, otherwise it will take unnecessarily long time for me to figure it out, and I will probably just give up if I dont get it to work, lazy as I am, and also afraid to be disturbing and irritating.

**Comment by ricrpi** [comment]
Since you have timescales to meet, I would recommend you try on a fresh install of Raspbian. Also don't be concerned about disturbing or irritating anyone, I would rather have the script working well. 

With regrds to Linux, I would rather not put you off it so if I'm not being very clear then please pull me up on it :-) 

If you want to continue debugging over the next day or so then a more descriptive list of instructions would be:
# log in
mv .bashrc .bashrc_backup
sudo reboot
# log in again
cd mupen64plus
V=1 ./build.sh 2>&1 | tee build.log

# if it doesn't work then do following:
nano +557 build.sh
# add the text 'set -x' onto a new/empty line 
# Prest Ctrl+X to save and quit nano
V=1 ./build.sh 2>&1 | tee build.log

You should be left with a log file (build.log) that you can either email to me (use 'git log' in mupen64plus build directory to find address) or post its contents. If you want to know more about what each command is doing feel free to ask
