### ISSUE TITLE
libmupen64plus.so.2.0.0 uses VFP register arguments, failed to merge target specific data

### ISSUE THREAD

**Issue by Narann** [ricrpi/mupen64plus#7]
Hello!

First, thanks for this script, very usefull. I try to compile using `./dev_build.sh` on my rpi and get this error:
```
    LD  libmupen64plus.so.2.0.0
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans0.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans0.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans1.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans1.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans2.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans2.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans3.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans3.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans4.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans4.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans5.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans5.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans6.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans6.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans7.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans7.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans8.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans8.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans9.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans9.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans10.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans10.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans11.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans11.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans12.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans12.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans13.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans13.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans14.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans14.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans15.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans15.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans16.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans16.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans17.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans17.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans18.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans18.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans19.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans19.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans20.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans20.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans21.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans21.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans22.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans22.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans23.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans23.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans24.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans24.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans25.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans25.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans26.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans26.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans27.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans27.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans28.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans28.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans29.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans29.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans30.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans30.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, /tmp/ccaP2mpO.ltrans31.ltrans.o does not
/usr/bin/ld: failed to merge target specific data of file /tmp/ccaP2mpO.ltrans31.ltrans.o
/usr/bin/ld: error: libmupen64plus.so.2.0.0 uses VFP register arguments, _obj/r4300/new_dynarec/linkage_arm.o does not
/usr/bin/ld: failed to merge target specific data of file _obj/r4300/new_dynarec/linkage_arm.o
collect2: error: ld returned 1 exit status
Makefile:604: recipe for target 'libmupen64plus.so.2.0.0' failed
make: *** [libmupen64plus.so.2.0.0] Error 1
make: Leaving directory '/home/pi/code/mupen64plus/ricrpi/mupen64plus-core/projects/unix'
```
It [seems](http://stackoverflow.com/questions/9753749/arm-compilation-error-vpf-registered-used-by-executable-not-object-file) to be related to hardfloat softfloat.

I'm using raspbian. My gcc-4.7 is:
```
$ gcc-4.7 -v
Using built-in specs.
COLLECT_GCC=gcc-4.7
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.7/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5+rpi1' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --enable-plugin --enable-objc-gc --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.7.2 (Debian 4.7.2-5+rpi1) 
```
Any idea?

Thanks in advance! :)

**Comment by ricrpi** [comment]
I will try testing next week but in the mean time you could try using CLEAN=1 ./dev_build.sh to do a clean first incase some files were built for soft-float. 

I fixed an error in the core makefile for soft/hard floating point yesterday so have you got that update?

**Comment by Narann** [comment]
Using `gitk --all` I realize the current repo status was using `origin/master` and not `origin/ric_dev` with some commits related to VFP stuff. So I manually checkout `origin/ric_dev` and it compiled without problem.

But after I run into some troubles:

```
************************************ Building core library
make: Entering directory '/home/pi/code/mupen64plus/ricrpi/mupen64plus-core/projects/unix'
Makefile:108: Architecture "armv6l" not officially supported.'
make: Nothing to be done for 'all'.
make: Leaving directory '/home/pi/code/mupen64plus/ricrpi/mupen64plus-core/projects/unix'
make: Entering directory '/home/pi/code/mupen64plus/ricrpi/mupen64plus-core/projects/unix'
Makefile:108: Architecture "armv6l" not officially supported.'
install -d "/home/pi/code/mupen64plus/test"
install -m 0644 -s libmupen64plus.so.2.0.0 "/home/pi/code/mupen64plus/test"
install -d "/home/pi/code/mupen64plus/test"
install -m 0644 ../../data/* "/home/pi/code/mupen64plus/test"
install -d "/home/pi/code/mupen64plus/testapi"
install -m 0644 ../../src/api/m64p_*.h "/home/pi/code/mupen64plus/testapi"
true "/home/pi/code/mupen64plus/test"
if [ ! -e "/home/pi/code/mupen64plus/test/libmupen64plus.so.2" ]; then ln -sf "libmupen64plus.so.2.0.0" "/home/pi/code/mupen64plus/test/libmupen64plus.so.2"; fi
make: Leaving directory '/home/pi/code/mupen64plus/ricrpi/mupen64plus-core/projects/unix'
************************************ Building ui-console front-end
make: Entering directory '/home/pi/code/mupen64plus/mupen64plus/mupen64plus-ui-console/projects/unix'
Makefile:87: Architecture "armv6l" not officially supported.'
Makefile:182: *** Mupen64Plus API header files not found! Use makefile parameter APIDIR to force a location..  Stop.
make: Leaving directory '/home/pi/code/mupen64plus/mupen64plus/mupen64plus-ui-console/projects/unix'
```
Ok, let's try with this:

    APIDIR=./ricrpi/mupen64plus-core/src/api/ ./dev_build.sh

```
************************************ Building ui-console front-end
make: Entering directory '/home/pi/code/mupen64plus/mupen64plus/mupen64plus-ui-console/projects/unix'
Makefile:87: Architecture "armv6l" not officially supported.'
    CC  _obj/cheat.o
../../src/cheat.c:27:24: fatal error: m64p_types.h: No such file or directory
compilation terminated.
Makefile:336: recipe for target '_obj/cheat.o' failed
make: *** [_obj/cheat.o] Error 1
make: Leaving directory '/home/pi/code/mupen64plus/mupen64plus/mupen64plus-ui-console/projects/unix'
```
And this:

    APIDIR=./testapi ./dev_build.sh 

Same problem.

And last chance:

    APIDIR=/home/pi/code/mupen64plus/testapi ./dev_build.sh 

It worked! (Notice the full path).

So, after compiling process I can finally run mupen64plus but:
```bash
$ ./mupen64plus ~/n64/roms/Super_Mario_64_U.z64 
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.0.0

UI-Console: attached to core library 'Mupen64Plus Core' version 2.0.0
UI-Console:             Includes support for Dynamic Recompiler.
Core: Goodname: Super Mario 64 (U) [!]
Core: Name: SUPER MARIO 64      
Core: MD5: 20B854B239203BAF6C961B850A4A51A2
Core: CRC: 635a2bff 8b022326
Core: Imagetype: .z64 (native)
Core: Rom size: 8388608 bytes (or 8 Mb or 64 Megabits)
Core: Version: 1444
Core: Manufacturer: Nintendo
Core: Country: USA
UI-Console Status: Cheat codes disabled.
UI-Console: using Video plugin: 'Mupen64Plus OpenGL Video Plugin by Rice' v2.0.0
UI-Console: using Audio plugin: <dummy>
UI-Console: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.0.0
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.0.0
Input: 0 SDL joysticks were found.
Input: N64 Controller #1: Forcing default keyboard configuration
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input Warning: Couldn't open rumble support for joystick #1
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.0.0 initialized.
Core Warning: No audio plugin attached.  There will be no sound output.
Video: Disabled SSE processing.
Video: Found ROM 'SUPER MARIO 64', CRC ff2b5a632623028b-45
Video: Initializing OpenGL Device Context.
Core Error: SDL video subsystem init failed: 
Core Status: Rom closed.
```
As you can see, SDL does not provide any message. In the core API, I think he crash [here](https://github.com/mupen64plus/mupen64plus-core/blob/master/src/api/vidext.c#L101) but it does not explain why SDL is unable to provide any info...

Also, I'm through `ssh -X`. I will test to plug the rpi directly but if you have any info it would be welcome! :)

**Comment by Narann** [comment]
Oh! I realize I installed `libgles2-mesa` packages to have rice compiling well. But I just found there is a bunch of rpi specific libs in `/opt/vc/lib` (with `libGLESv2.so`). Should I remove my `libgles2-mesa` packages and use _vc_ ones instead?

A big thanks in advance! :)

**Comment by Narann** [comment]
Ok, I've tested witb `/opt/vc/include`, `/opt/vc/lib` still doesn't work.
Plug the rpi to a real screen and a real keyboard (no ssh), same problem. :(

**Comment by ricrpi** [comment]
I thought the APIDIR problem was resolved. The path would be relative from the Makefile location e.g. mupen64plus-core/projects/unix/

You need to use the /opt/vc/lib files in order to utilize the GPU. mesa will only do software rendering. ( I think there is a project to get hardware acceleration into mesa for the pi though).

Have you configured SDL2 with the following:
./configure --disable-video-opengl --disable-video-x11

SDL2 will then try and use GLES2 instead of OpenGL. 

Also I don't think SDL2 can setup/display a GLES2 context within X11 so X11 has to be disabled due to how SDL checks/chooses the video driver to use. if you have other applications that use SDL2/X11 you may break them if you do this though.

**Comment by Narann** [comment]
Thanks @ricrpi, I will check all of this. About SDL2, I saw your script retrieve SDL2 trackball and compile it itself. Can you confirm me it was using the args you just provide? Where can I check SDL2 have been compiled with such flags?

About X, I tested with both X started and without (in console).

I will still investigate and keep you up. I really hope I will have my plugin running on rpi. :)

**Comment by ricrpi** [comment]
if you use `X11=2 ./build.sh` the script will check and rebuild SDL2 correctly for you i.e. without X11 and with GLES.

You can manually check the installed SDL libraries by looking through /usr/local/include/SDL2/SDL_config.h. Look for SDL_VIDEO_OPENGL_ES2 and SDL_VIDEO_DRIVER_X11,

**Comment by Narann** [comment]
Thanks @ricrpi I dig into all of this yesterday and finally decide to manually compile everything. :D

I finally had a `undefined reference to 'SDL_DestroyWindow'` which [seems](https://stackoverflow.com/questions/18449697/sdl2-undefined-references-to-functions) to be related to a SDL flag compilation order. I will try to change the `Makefile` bringing good SDL order and recompile.

**Comment by Narann** [comment]
Then I finally solve this `undefined reference` problems then I fall back on:
```
Video: Initializing OpenGL Device Context.
Core Error: SDL video subsystem init failed: 
Core Status: Rom closed.
```
I will have to clean everything and test the original code because it can be my Rice port wich break everything. Focusing on having anything working would help me to focus on what's wrong with my Rice version later...

Anyway, technically this issue is solved! Thanks for all the informations.
